name: release

on:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE }}
      run: msbuild /m /p:Configuration=Release /p:Platform=x86 /t:xdead

    - name: Create archive
      run: 7z a xdead-${{ github.ref_name }}.zip ./bin/Release/xlive.dll

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        name: XDead ${{ github.ref_name }}
        body: |
          [READ tested games first](https://github.com/NeKzor/xdead#tested-games)
          [Download xdead-${{ github.ref_name }}.zip](https://github.com/NeKzor/xdead/releases/download/${{ github.ref_name }}/xdead-${{ github.ref_name }}.zip)
        files: xdead-${{ github.ref_name }}.zip
        prerelease: ${{ contains(github.ref, 'pre') }}
